-- =====================================================================================
-- IronFlow V1 - Core persistence schema.
--
-- Design notes:
--   * Enums are modelled as TEXT + CHECK rather than native PG enums. Native enums
--     require ALTER TYPE for new values, which takes heavier locks and complicates
--     zero-downtime deploys; CHECK constraints can be swapped with NOT VALID +
--     VALIDATE. They also map trivially to Java enums without a custom converter.
--   * Timestamps are TIMESTAMPTZ everywhere. A durable execution engine that stores
--     naive timestamps will fire timers an hour late twice a year.
--   * Payloads are JSONB in wf_events (queryable history, worth the parse cost on
--     write) and BYTEA in wf_tasks (opaque transport, never queried, avoids double
--     encoding).
--   * Identity columns use GENERATED BY DEFAULT AS IDENTITY rather than BIGSERIAL:
--     SQL-standard, no orphaned sequence ownership, and correct interaction with
--     Hibernate's GenerationType.IDENTITY.
-- =====================================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- -------------------------------------------------------------------------------------
-- wf_executions - one row per workflow instance. Mutable projection of event history.
-- -------------------------------------------------------------------------------------
CREATE TABLE wf_executions (
    id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    workflow_type    TEXT        NOT NULL,
    business_key     TEXT,
    status           TEXT        NOT NULL DEFAULT 'RUNNING',
    -- Optimistic lock. Every decision commit does UPDATE ... WHERE current_version = ?
    -- and asserts rowcount = 1. This is the serialization point for a single execution.
    current_version  BIGINT      NOT NULL DEFAULT 0,
    -- High-water mark for wf_events.sequence_number. Reserved (not read-then-written)
    -- inside the commit transaction so ids are gap-free and monotonic per execution.
    next_sequence    BIGINT      NOT NULL DEFAULT 1,
    input            BYTEA,
    result           BYTEA,
    failure          TEXT,
    start_time       TIMESTAMPTZ NOT NULL DEFAULT now(),
    end_time         TIMESTAMPTZ,

    CONSTRAINT ck_wf_exec_status CHECK (
        status IN ('RUNNING','COMPLETED','FAILED','CANCELLED','TIMED_OUT')),
    -- Terminal states must carry an end_time; non-terminal states must not.
    CONSTRAINT ck_wf_exec_end_time CHECK (
        (status = 'RUNNING') = (end_time IS NULL)),
    CONSTRAINT ck_wf_exec_version CHECK (current_version >= 0),
    CONSTRAINT ck_wf_exec_next_seq CHECK (next_sequence >= 1)
);

-- Dedupe guard for client-supplied idempotency. A partial unique index (rather than a
-- plain UNIQUE) so that unbounded NULL business_keys cost nothing in the index.
CREATE UNIQUE INDEX uq_wf_exec_business_key
    ON wf_executions (business_key)
    WHERE business_key IS NOT NULL;

-- Operator/UI query path: "show me running workflows of type X, newest first".
CREATE INDEX idx_wf_exec_type_status
    ON wf_executions (workflow_type, status, start_time DESC);

-- Reaper path: find executions stuck open past a deadline.
CREATE INDEX idx_wf_exec_open
    ON wf_executions (start_time)
    WHERE status = 'RUNNING';

-- -------------------------------------------------------------------------------------
-- wf_tasks - the native queue. No broker. Both decision and activity tasks live here.
-- -------------------------------------------------------------------------------------
CREATE TABLE wf_tasks (
    id                  BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id        UUID        NOT NULL
                        REFERENCES wf_executions (id) ON DELETE CASCADE,
    task_queue          TEXT        NOT NULL,
    kind                TEXT        NOT NULL,
    status              TEXT        NOT NULL DEFAULT 'PENDING',
    -- Links the task back to the ACTIVITY_SCHEDULED / TIMER_STARTED event that created
    -- it. Used both for dedupe and to resolve the task's input during replay.
    scheduled_event_seq BIGINT      NOT NULL,
    -- Lease fields. lease_owner is a per-lease token, NOT a worker identity: a worker
    -- that loses and re-acquires a lease gets a fresh token, so its stale in-flight ack
    -- is rejected.
    lease_owner         UUID,
    lease_until         TIMESTAMPTZ,
    -- Visibility timestamp. Timers and retry backoff are both expressed here, which is
    -- why IronFlow needs no separate scheduler subsystem.
    not_before          TIMESTAMPTZ NOT NULL DEFAULT now(),
    attempt             INT         NOT NULL DEFAULT 1,
    max_attempts        INT         NOT NULL DEFAULT 5,
    payload             BYTEA,
    last_failure        TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT ck_wf_task_kind   CHECK (kind IN ('WORKFLOW','ACTIVITY','TIMER')),
    CONSTRAINT ck_wf_task_status CHECK (
        status IN ('PENDING','LEASED','COMPLETED','FAILED','CANCELLED')),
    CONSTRAINT ck_wf_task_attempt CHECK (attempt >= 1 AND attempt <= max_attempts + 1),
    -- A LEASED task must carry a full lease; anything else must carry none. This makes
    -- "leased but no expiry" - the state that silently wedges a queue forever -
    -- unrepresentable rather than merely unlikely.
    CONSTRAINT ck_wf_task_lease CHECK (
        (status = 'LEASED') = (lease_owner IS NOT NULL AND lease_until IS NOT NULL))
);

-- ---------------------------------------------------------------------------
-- Hot path index. Every poller hits exactly this, many times per second.
--
-- Column order is dictated by the dispatch predicate:
--   equality (task_queue, kind) -> range (not_before) -> tiebreak (id)
-- Reversing range and tiebreak forces a filter instead of an index range scan.
--
-- The partial predicate is what makes this scale: COMPLETED tasks accumulate
-- without bound, but they leave the index entirely, so index size tracks queue
-- *depth*, not queue *throughput*. On a backlog of 10M completed and 200 pending,
-- this index holds 200 entries.
-- ---------------------------------------------------------------------------
CREATE INDEX idx_wf_tasks_poll
    ON wf_tasks (task_queue, kind, not_before, id)
    WHERE status = 'PENDING';

-- Reaper path: reclaim leases from crashed workers. Also partial - only LEASED rows
-- are candidates, so this stays tiny regardless of table size.
CREATE INDEX idx_wf_tasks_expired_lease
    ON wf_tasks (lease_until)
    WHERE status = 'LEASED';

-- Per-execution lookup (cancellation cascade, admin inspection, replay resolution).
CREATE INDEX idx_wf_tasks_execution
    ON wf_tasks (execution_id, scheduled_event_seq);

-- Enqueue dedupe: a decision replayed after a lost ack must not double-schedule.
-- Covers only live tasks so that a retried-then-completed task can be re-created
-- by continue-as-new without tripping the constraint.
CREATE UNIQUE INDEX uq_wf_tasks_scheduled
    ON wf_tasks (execution_id, scheduled_event_seq, kind)
    WHERE status IN ('PENDING','LEASED');

-- ---------------------------------------------------------------------------
-- THE structural invariant of the engine: at most one open decision task per
-- execution. Concurrent signals cannot race to enqueue a second one - the second
-- INSERT fails on this index, and the caller instead appends its event to history
-- for the already-pending decision to observe.
--
-- Exactly-once decision processing is therefore enforced by the *schema*, not by
-- application-level care.
-- ---------------------------------------------------------------------------
CREATE UNIQUE INDEX uq_wf_tasks_one_open_decision
    ON wf_tasks (execution_id)
    WHERE kind = 'WORKFLOW' AND status IN ('PENDING','LEASED');

-- High-churn table: every row is inserted, updated 2-4 times, and eventually dead.
-- Aggressive autovacuum and headroom for HOT updates keep bloat bounded.
ALTER TABLE wf_tasks SET (
    fillfactor = 70,
    autovacuum_vacuum_scale_factor = 0.01,
    autovacuum_analyze_scale_factor = 0.01,
    autovacuum_vacuum_cost_delay = 0
);

-- -------------------------------------------------------------------------------------
-- wf_events - append-only history. The source of truth; everything else is a projection.
-- -------------------------------------------------------------------------------------
CREATE TABLE wf_events (
    id               BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id     UUID        NOT NULL
                     REFERENCES wf_executions (id) ON DELETE CASCADE,
    sequence_number  BIGINT      NOT NULL,
    event_type       TEXT        NOT NULL,
    payload          JSONB       NOT NULL DEFAULT '{}'::jsonb,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT ck_wf_events_seq CHECK (sequence_number >= 1)
);

-- Gap-free, collision-free ordering per execution. This is the replay contract: read
-- WHERE execution_id = ? ORDER BY sequence_number and you get the exact stream the
-- workflow saw last time. Also the dedupe guard against double-append on retry.
CREATE UNIQUE INDEX uq_wf_events_seq
    ON wf_events (execution_id, sequence_number);

-- Analytics / debugging by event class without scanning history.
CREATE INDEX idx_wf_events_type
    ON wf_events (event_type, created_at DESC);

-- -------------------------------------------------------------------------------------
-- Append-only enforcement. Application bugs must not be able to rewrite history -
-- if history is mutable, replay is not deterministic and the entire guarantee collapses.
-- -------------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION wf_events_reject_mutation() RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION
        'wf_events is append-only; % on execution % seq % rejected',
        TG_OP, OLD.execution_id, OLD.sequence_number
        USING ERRCODE = 'integrity_constraint_violation';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_wf_events_immutable
    BEFORE UPDATE OR DELETE ON wf_events
    FOR EACH ROW EXECUTE FUNCTION wf_events_reject_mutation();

-- Note: DELETE via ON DELETE CASCADE from wf_executions will also be rejected by this
-- trigger. That is intentional - purging an execution is an explicit admin operation
-- that must go through a maintenance path (ALTER TABLE ... DISABLE TRIGGER), not an
-- accidental consequence of deleting a parent row. See V2 for the purge helper.

CREATE OR REPLACE FUNCTION wf_touch_updated_at() RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_wf_tasks_touch
    BEFORE UPDATE ON wf_tasks
    FOR EACH ROW EXECUTE FUNCTION wf_touch_updated_at();
