-- =====================================================================================
-- V5 - External signals and hardened start idempotency.
-- =====================================================================================

-- -------------------------------------------------------------------------------------
-- Input fingerprinting for idempotent start.
--
-- The problem this solves is not the happy-path duplicate - that already works via
-- uq_wf_exec_business_key. It is the case where a caller reuses a business key with
-- DIFFERENT input, usually because the key is less unique than they thought
-- ("order-123" colliding across tenants), or because a retry carries a mutated payload.
--
-- Without a fingerprint we silently return an execution running someone else's input, and
-- the caller believes their request was accepted. Storing a hash lets us distinguish
-- "your retry" from "your key collided" and fail loudly on the latter.
--
-- A hash rather than the input itself: inputs can be large, this column is read on every
-- duplicate start, and we only ever need equality.
-- -------------------------------------------------------------------------------------
ALTER TABLE wf_executions
    ADD COLUMN input_fingerprint TEXT;

UPDATE wf_executions
   SET input_fingerprint = encode(sha256(COALESCE(input, ''::bytea)), 'hex')
 WHERE business_key IS NOT NULL AND input_fingerprint IS NULL;

-- -------------------------------------------------------------------------------------
-- Signal delivery deduplication.
--
-- Signals arrive over HTTP, and HTTP clients retry. Without a dedupe key, a client that
-- times out and retries delivers the same signal twice, and the workflow sees two
-- approvals where a human clicked once.
--
-- Scoped per execution rather than globally: two different orders may legitimately share
-- a caller-generated signal id, and a global constraint would reject the second.
-- -------------------------------------------------------------------------------------
CREATE TABLE wf_signal_dedupe (
    execution_id    UUID        NOT NULL REFERENCES wf_executions (id) ON DELETE CASCADE,
    signal_id       TEXT        NOT NULL,
    sequence_number BIGINT      NOT NULL,
    received_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (execution_id, signal_id)
);

-- -------------------------------------------------------------------------------------
-- Signals for workflows that have not started yet.
--
-- A real ordering hazard: "create order" and "cancel order" are separate calls over
-- separate connections, and nothing guarantees the create commits first. Rejecting the
-- early signal pushes a distributed-systems problem onto every API caller.
--
-- Instead we buffer. A signal for an unknown execution is held here, and start() drains
-- the buffer into history as part of the same transaction that creates the execution, so
-- a signal can never be lost in the gap.
-- -------------------------------------------------------------------------------------
CREATE TABLE wf_pending_signals (
    id           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_key TEXT        NOT NULL,
    signal_name  TEXT        NOT NULL,
    signal_id    TEXT,
    payload      JSONB       NOT NULL DEFAULT '{}'::jsonb,
    received_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at   TIMESTAMPTZ NOT NULL DEFAULT now() + INTERVAL '24 hours'
);

CREATE INDEX idx_pending_signals_key ON wf_pending_signals (business_key);

-- Bounded lifetime. Without expiry this table accumulates signals for executions that
-- were never created - a typo'd business key would leave a row forever.
-- NOTE: a sweep must actually purge these. See PendingSignalReaper.
CREATE INDEX idx_pending_signals_expiry ON wf_pending_signals (expires_at);

CREATE UNIQUE INDEX uq_pending_signals_dedupe
    ON wf_pending_signals (business_key, signal_id)
    WHERE signal_id IS NOT NULL;
